export type {
  AssignDepartmentBody,
  CreateReportBody,
  Department,
  DepartmentInfo,
  ListReportsParams,
  ReportCategory,
  ReportDetail,
  ReportImage,
  ReportResponse,
  ReportSeverity,
  ReportStatus,
  StatusEvent,
  TrackingReport,
  UpdateStatusBody,
  UploadImageResponse,
} from "@/lib/api";
